name: Daily Morning Message

on:
  schedule:
    # 每天北京时间早上8点运行 (UTC时间0点)
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  send-morning-message:
    runs-on: ubuntu-latest
    name: Send daily message to girlfriend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run daily message script
      env:
        SEND_KEY: ${{ secrets.SEND_KEY }}
        CITY: ${{ secrets.CITY }}
        BIRTHDAY: ${{ secrets.BIRTHDAY }}
        GF_NAME: ${{ secrets.GF_NAME }}
      run: python daily_message.py
      
    - name: Notify success
      if: success()
      run: echo "✅ Daily message sent successfully!"
      
    - name: Notify failure
      if: failure()
      run: echo "❌ Failed to send daily message"
